version: '3.3'

services:
  business-central-workbench:
    image: hrabosch.droolsrules:latest
    ports:
      - 8001:8001
      - 8080:8080
    container_name: business-central-workbench
    volumes:
      - ./wb-git:/opt/jboss/wildfly/bin/.niogit:Z
    networks:
      - local-drools-network
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - local-drools-network
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8082:3000
      - 2222:22


networks:
  local-drools-network:
    name: local-drools-network