version: '3.3'

services:
  business-central-workbench:
    image: hrabosch.business-central-workbench:latest
    ports:
      - 8001:8001
      - 8080:8080
    container_name: business-central-workbench
    volumes:
      - ./wb-git:/opt/jboss/wildfly/bin/.niogit:Z
      - ./.m2:/opt/jboss/.m2/
    networks:
      - local-drools-network
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - local-drools-network
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 22:22
  kie-server:
    image: hrabosch.kie-server:latest
    container_name: kie-server
    ports:
      - 8088:8080
    networks:
      - local-drools-network
    volumes:
      - ./.m2:/opt/jboss/.m2/
    depends_on:
      - business-central-workbench
networks:
  local-drools-network:
    name: local-drools-network
    